[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "data-driven-eft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "givernylocal>=3.6.2",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "scipy>=1.18.1",
    "torch>=2.14.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest",
    "ruff",
]

[tool.pyright]
typeCheckingMode = "basic"

[tool.setuptools.packages.find]
where = ["src"]
